### ISSUE TITLE
Readme/Documentation: Feedback

### ISSUE THREAD

**Issue by MikeVezina** [SYSC3110-Team-Best/RISK#8]
- You are missing your design choices and data structure explanations. (For example: why did you choose ArrayList for players, countries, etc. instead of a Map, and why is your choice better or worse?)

- Please include known issues and a roadmap for future milestones. Even if you have no known issues, you need to state that!

**Comment by tiaaanlin** [comment]
I already added sections about 1)design choices 2)data structure 3)known issue in readme and will fill in next milestone.
